package actividad13;
// Generated 6/05/2019 05:12:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Date dateCreated;
     private Boolean isAdmin;
     private Integer numPoints;

    public Users() {
    }

	
    public Users(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Users(String firstName, String lastName, Date dateCreated, Boolean isAdmin, Integer numPoints) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.dateCreated = dateCreated;
       this.isAdmin = isAdmin;
       this.numPoints = numPoints;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Integer getNumPoints() {
        return this.numPoints;
    }
    
    public void setNumPoints(Integer numPoints) {
        this.numPoints = numPoints;
    }




}


